version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: betus040204
      MYSQL_DATABASE: your_database
      MYSQL_USER: root
      MYSQL_PASSWORD: betus040204
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: